apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: somelabelvalue
  namespace: jenkins
spec:
  containers:
  - name: buildah
    image: quay.io/buildah/stable:latest
    imagePullPolicy: "Always"
    command:
    - sleep
    args:
    - 99d
    env:
      - name: STORAGE_DRIVER
        value: "vfs"
    securityContext:
      capabilities:
        add:
          - 'CHOWN'
          - 'DAC_OVERRIDE'
          - 'FSETID'
          - 'FOWNER'
          - 'MKNOD'
          - 'SETGID'
          - 'SETUID'
          - 'SETFCAP'
          - 'SETPCAP'
          - 'NET_BIND_SERVICE'
          - 'SYS_CHROOT'
          - 'KILL'
          - 'AUDIT_WRITE'
          - 'MKNOD'
          - 'SETUID'
          - 'SETGID'
          - 'SYS_CHROOT'
  - name: kubectl
    image: quay.io/karmab/kubectl
    command:
    - sleep
    args:
    - 999999
