apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: somelabelvalue
  namespace: jenkins
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildah: unconfined
spec:
  containers:
  - name: buildah
    image: quay.io/buildah/stable:latest
    imagePullPolicy: "Always"
    command:
    - sleep
    args:
    - 99d
    securityContext:
      capabilities:
        add:
          - 'CHOWN'
          - 'DAC_OVERRIDE'
          - 'FSETID'
          - 'FOWNER'
          - 'MKNOD'
          - 'SETGID'
          - 'SETUID'
          - 'SETFCAP'
          - 'SETPCAP'
          - 'NET_BIND_SERVICE'
          - 'SYS_CHROOT'
          - 'KILL'
          - 'AUDIT_WRITE'
          - 'MKNOD'
          - 'SETUID'
          - 'SETGID'
          - 'SYS_CHROOT'
    volumeMounts:
    - name: buildah-auth
      mountPath: /buildah-auth
  - name: kubectl
    image: quay.io/karmab/kubectl
    command:
    - sleep
    args:
    - 999999
  volumes:
  - name: buildah-auth
    configMap:
      name: buildah-auth
