apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: somelabelvalue
  namespace: jenkins
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildah: unconfined
spec:
  containers:
  - name: buildah
    image: quay.io/buildah/stable:latest
    imagePullPolicy: "Always"
    command:
    - sleep
    args:
    - 99d
    securityContext:
      capabilities:
        add:  #["SYS_ADMIN", "MKNOD"]
         - ALL
#        privileged: true   ###Here is what you are looking for
